# Generated by Django 5.1.4 on 2026-10-07 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('level', models.IntegerField(choices=[(0, 'Faible'), (1, 'Moyen'), (2, 'Élevé')])),
                ('source', models.CharField(choices=[('risque', 'Risque prévu'), ('anomalie', 'Anomalie constatée')], max_length=10)),
                ('status', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('prise_en_compte', 'Prise en compte'), ('resolue', 'Résolue')], default='nouvelle', max_length=16)),
                ('undercap_probability', models.FloatField(null=True)),
                ('expected_loss', models.FloatField(null=True)),
                ('recommended_reinforcement', models.PositiveSmallIntegerField(default=0)),
                ('observed_volume', models.FloatField(help_text='Pour une anomalie', null=True)),
                ('expected_volume', models.FloatField(null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('handling_comment', models.TextField(blank=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='planning.staffingplan')),
            ],
            options={
                'ordering': ['-level', 'start'],
                'indexes': [models.Index(fields=['date', 'status'], name='alerts_aler_date_9c2bd4_idx')],
            },
        ),
    ]
