# Generated by Django 5.1.4 on 2026-10-07 23:51

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSlot',
            fields=[
                ('ts', models.DateTimeField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('day_of_week', models.SmallIntegerField()),
                ('period_index', models.SmallIntegerField()),
                ('is_weekend', models.BooleanField()),
                ('is_holiday', models.BooleanField()),
                ('holiday_name', models.CharField(max_length=80, null=True)),
                ('is_school_holiday', models.BooleanField()),
                ('season', models.CharField(max_length=10)),
            ],
            options={
                'db_table': '"ref"."calendar"',
                'ordering': ['ts'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_ts', models.DateTimeField()),
                ('end_ts', models.DateTimeField()),
                ('event_type', models.CharField(max_length=40)),
                ('intensity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': '"ref"."events"',
                'ordering': ['start_ts'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IntervalMetric',
            fields=[
                ('ts', models.DateTimeField(primary_key=True, serialize=False)),
                ('offered', models.IntegerField()),
                ('answered', models.IntegerField()),
                ('abandoned', models.IntegerField()),
                ('avg_wait_seconds', models.DecimalField(decimal_places=2, max_digits=8)),
                ('avg_handle_seconds', models.DecimalField(decimal_places=2, max_digits=8)),
                ('agents_scheduled', models.SmallIntegerField()),
                ('agents_present', models.SmallIntegerField()),
                ('agents_absent', models.SmallIntegerField()),
                ('service_level', models.DecimalField(decimal_places=4, max_digits=5)),
                ('abandon_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('occupancy', models.DecimalField(decimal_places=4, max_digits=5)),
                ('csat_mean', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('csat_responses', models.SmallIntegerField()),
                ('is_imputed', models.BooleanField()),
                ('imputed_columns', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
            ],
            options={
                'db_table': '"core"."interval_metrics"',
                'ordering': ['ts'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('param_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit', models.CharField(max_length=30)),
                ('source', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"ref"."cost_parameters"',
                'ordering': ['param_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParameterChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=50)),
                ('old_value', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('new_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
