# Generated by Django 5.1.4 on 2026-10-07 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'état de la plateforme',
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40, unique=True)),
                ('cutoff', models.DateField(help_text="Le modele n'a vu aucune donnee posterieure.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('file_path', models.CharField(max_length=200)),
                ('metrics', models.JSONField(default=dict, help_text='WAPE, biais, couverture... hors echantillon')),
                ('card', models.JSONField(default=dict, help_text="Fiche d'identite complete du modele")),
            ],
            options={
                'ordering': ['-cutoff'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='un_seul_modele_actif')],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cycle_quotidien', 'Cycle quotidien'), ('reentrainement', 'Réentraînement'), ('import', 'Import de données'), ('replanification', 'Replanification')], max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('en_cours', 'En cours'), ('succes', 'Succès'), ('echec', 'Échec')], default='en_cours', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('steps', models.JSONField(default=list, help_text='Etapes executees et leur duree')),
                ('message', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_expected', models.FloatField()),
                ('total_q10', models.FloatField(null=True)),
                ('total_q90', models.FloatField(null=True)),
                ('model_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.modelversion')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.pipelinerun')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StaffingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('actuel', 'Planning actuel (outil WFM)'), ('ia', 'IA seule'), ('recommande', 'Recommandé (IA + risque)'), ('ajuste', 'Ajusté manuellement'), ('scenario', "Issu d'un scénario what-if")], max_length=12)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis à validation'), ('valide', 'Validé'), ('publie', 'Publié'), ('remplace', 'Remplacé')], default='brouillon', max_length=10)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('alpha', models.FloatField(blank=True, help_text='Risque de sous-capacite tolere', null=True)),
                ('scenario', models.JSONField(blank=True, default=dict, help_text='Hypotheses what-if eventuelles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_hours', models.FloatField(null=True)),
                ('cost_agents', models.FloatField(null=True)),
                ('expected_loss', models.FloatField(null=True)),
                ('var95', models.FloatField(null=True)),
                ('es95', models.FloatField(null=True)),
                ('expected_service_level', models.FloatField(null=True)),
                ('max_undercap_probability', models.FloatField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('forecast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.dailyforecast')),
                ('parent', models.ForeignKey(blank=True, help_text='Planning dont celui-ci est derive (ajustement, scenario)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='planning.staffingplan')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('agents', models.PositiveSmallIntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='planning.staffingplan')),
            ],
            options={
                'ordering': ['start', 'end'],
            },
        ),
        migrations.CreateModel(
            name='PlanInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('agents_required', models.PositiveSmallIntegerField(help_text="Besoin issu de l'optimisation")),
                ('agents_scheduled', models.PositiveSmallIntegerField(help_text='Agents couverts par les vacations')),
                ('undercap_probability', models.FloatField(null=True)),
                ('expected_loss', models.FloatField(null=True)),
                ('expected_service_level', models.FloatField(null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='planning.staffingplan')),
            ],
            options={
                'ordering': ['ts'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('cree', 'Créé'), ('ajuste', 'Ajusté'), ('soumettre', 'Soumis'), ('refuser', 'Refusé'), ('valider', 'Validé'), ('publier', 'Publié'), ('remplace', 'Remplacé'), ('renfort', 'Renfort appliqué'), ('export', 'Exporté')], max_length=12)),
                ('comment', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='planning.staffingplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntervalForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('expected', models.FloatField()),
                ('q01', models.FloatField()),
                ('q10', models.FloatField()),
                ('q50', models.FloatField()),
                ('q90', models.FloatField()),
                ('q99', models.FloatField()),
                ('aht_expected', models.FloatField()),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='planning.dailyforecast')),
            ],
            options={
                'ordering': ['ts'],
                'constraints': [models.UniqueConstraint(fields=('forecast', 'ts'), name='une_prevision_par_demi_heure')],
            },
        ),
        migrations.AddConstraint(
            model_name='staffingplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'publie')), fields=('date',), name='un_seul_planning_publie_par_jour'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='vacation_fin_apres_debut'),
        ),
        migrations.AddConstraint(
            model_name='planinterval',
            constraint=models.UniqueConstraint(fields=('plan', 'ts'), name='une_ligne_par_demi_heure'),
        ),
    ]
