# Generated by Django 5.1.4 on 2026-10-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffingplan',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text="Vacations (solveur, ecart a l'optimum), comparaison au besoin ideal"),
        ),
    ]
