# Generated by Django 5.1.4 on 2026-10-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_staffingplan_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyforecast',
            name='level_total',
            field=models.FloatField(help_text='Total journalier prevu par le SARIMAX', null=True),
        ),
        migrations.AddField(
            model_name='intervalforecast',
            name='explanation',
            field=models.JSONField(blank=True, default=dict, help_text='Effet de chaque facteur, en %'),
        ),
    ]
